# Generated by Django 5.0.1 on 2024-01-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_backgroundimage_tattooimg_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('price_range', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_page_link', models.URLField()),
                ('photo', models.URLField()),
            ],
        ),
    ]
