# Generated by Django 5.0.1 on 2024-01-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tattooshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattooimg',
            name='img',
            field=models.ImageField(upload_to='tattoo_imgs'),
        ),
    ]
